### ISSUE TITLE
Debounce window resizer

### ISSUE THREAD

**Issue by tgrrtt** [anthonychu/angular-fill-height-directive#1]
Hi, I was thinking this could use a debounced window resizing function, as this event triggers differently on different browsers, (chrome triggers window resize multiple times, inconsistently, as it resizes, and firefox at the end of resize), and this would also ultimately lead to a more accurate div height.

If I implemented this would you be willing to merge it in?

**Comment by anthonychu** [comment]
For sure! That sounds great. Thanks.
